variables:
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  DOTNET_CSHARP_PROJECT_FOLDER: 'technical-starters/dotnet/kata-csharp'

.dotnet-csharp:
  extends: .only-default
  image: mcr.microsoft.com/dotnet/sdk:6.0
  only:
    changes:
      - 'dotnet/kata-csharp/**'
      - '.gitlab-ci.yml'

build:dotnet-csharp:
  extends:
    - .dotnet-csharp
  needs: [ ]
  stage: build
  before_script:
    - cd $DOTNET_CSHARP_PROJECT_FOLDER
  script: dotnet build

test:dotnet-csharp:
  extends:
    - .dotnet-csharp
  needs: [ "build:dotnet-csharp" ]
  stage: test
  before_script:
    - cd $DOTNET_CSHARP_PROJECT_FOLDER
  script: dotnet test