variables:
  KATA_ROMAN_NUMERALS_TS_FOLDER: 'kata-starters/kata-roman-numerals/typescript'

build:kata-bowling-ts:
  extends:
    - .typescript-npm
    - .only-default
  needs: [ ]
  stage: build
  before_script:
    - cd $KATA_ROMAN_NUMERALS_TS_FOLDER
  script:
    - npm install
    - npm run compile
  only:
    changes:
      - 'kata-starters/kata-roman-numerals/typescript/*'
      - 'kata-starters/kata-roman-numerals/typescript/**/*'

test:kata-bowling-ts:
  extends:
    - .typescript-npm
    - .only-default
  needs: [ "build:kata-bowling-ts" ]
  stage: test
  before_script:
    - cd $KATA_ROMAN_NUMERALS_TS_FOLDER
  script:
    - npm install
    - npm run test
  only:
    changes:
      - 'kata-starters/kata-roman-numerals/typescript/*'
      - 'kata-starters/kata-roman-numerals/typescript/**/*'
