variables:
  KATA_ROMAN_NUMERALS_JAVA_FOLDER: 'kata-starters/kata-roman-numerals/java'

build:kata-roman-numerals:
  extends:
    - .maven
    - .only-default
  needs: [ ]
  stage: build
  before_script:
    - cd $KATA_ROMAN_NUMERALS_JAVA_FOLDER
  script: mvn $MAVEN_CLI_OPTS test-compile
  only:
    changes:
      - 'kata-starters/kata-roman-numerals/java/*'
      - 'kata-starters/kata-roman-numerals/java/**/*'

test:kata-roman-numerals:
  extends:
    - .maven
    - .only-default
  needs: [ "build:kata-roman-numerals" ]
  stage: test
  before_script:
    - cd $KATA_ROMAN_NUMERALS_JAVA_FOLDER
  script: mvn $MAVEN_CLI_OPTS verify
  only:
    changes:
      - 'kata-starters/kata-roman-numerals/java/*'
      - 'kata-starters/kata-roman-numerals/java/**/*'
