name: Javascript NPM CI Workflow

inputs:
  project-folder:
    description: Javascript NPM project folder
    required: true
    default: 'starters/technical-starters/javascript/node-lts-24/vitest'
  npm-cli-opts:
    description: NPM CLI options
    required: false
    default: '--no-audit'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: install:npm-ts
      shell: sh
      run: npm ${{ inputs.npm-cli-opts }} ci
      working-directory: ${{ inputs.project-folder }}

    - name: test:npm-ts
      shell: sh
      run: npm ${{ inputs.npm-cli-opts }} run test
      working-directory: ${{ inputs.project-folder }}