variables:
  TS_NPM_PROJECT_FOLDER: 'technical-starters/typescript/npm'

cache:
  paths:
    - typescript/npm/node_modules/

.typescript-npm:
  extends: .only-default
  image: node:erbium-alpine
  only:
    changes:
      - 'typescript/npm/**'
      - '.gitlab-ci.yml'

build:typescript:npm:
  extends:
    - .typescript-npm
  needs: [ ]
  stage: build
  before_script:
    - cd $TS_NPM_PROJECT_FOLDER
  script:
    - npm install
    - npm run compile

test:typescript:npm:
  extends:
    - .typescript-npm
  needs: [ "build:typescript:npm" ]
  stage: test
  before_script:
    - cd $TS_NPM_PROJECT_FOLDER
  script:
    - npm install
    - npm run test
