variables:
  KATA_BOWLING_TS_FOLDER: 'kata-starters/kata-bowling/typescript'

build:kata-bowling-ts:
  extends:
    - .typescript-npm
    - .only-default
  needs: [ ]
  stage: build
  before_script:
    - cd $KATA_BOWLING_TS_FOLDER
  script:
    - npm install
    - npm run compile
  only:
    changes:
      - 'kata-starters/kata-bowling/typescript/*'
      - 'kata-starters/kata-bowling/typescript/**/*'

test:kata-bowling-ts:
  extends:
    - .typescript-npm
    - .only-default
  needs: [ "build:kata-bowling-ts" ]
  stage: test
  before_script:
    - cd $KATA_BOWLING_TS_FOLDER
  script:
    - npm install
    - npm run test
  only:
    changes:
      - 'kata-starters/kata-bowling/typescript/*'
      - 'kata-starters/kata-bowling/typescript/**/*'
