variables:
  KATA_RPG_FOLDER: 'kata-rpg'

build:kata-rpg:
  extends:
    - .maven
    - .only-default
  needs: [ ]
  stage: build
  before_script:
    - cd $KATA_RPG_FOLDER
  script: mvn $MAVEN_CLI_OPTS test-compile
  only:
    changes:
      - 'kata-rpg/*'
      - 'kata-rpg/**/*'

test:kata-rpg:
  extends:
    - .maven
    - .only-default
  needs: [ "build:kata-rpg" ]
  stage: test
  before_script:
    - cd $KATA_RPG_FOLDER
  script: mvn $MAVEN_CLI_OPTS verify
  only:
    changes:
      - 'kata-rpg/*'
      - 'kata-rpg/**/*'
