variables:
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  DOTNET_FSHARP_PROJECT_FOLDER: 'technical-starters/dotnet/kata-fsharp'

.dotnet-fsharp:
  extends: .only-default
  image: mcr.microsoft.com/dotnet/sdk:6.0
  only:
    changes:
      - 'dotnet/kata-fsharp/**'
      - '.gitlab-ci.yml'

build:dotnet-fsharp:
  extends:
    - .dotnet-fsharp
  needs: [ ]
  stage: build
  before_script:
    - cd $DOTNET_FSHARP_PROJECT_FOLDER
  script: dotnet build

test:dotnet-fsharp:
  extends:
    - .dotnet-fsharp
  needs: [ "build:dotnet-fsharp" ]
  stage: test
  before_script:
    - cd $DOTNET_FSHARP_PROJECT_FOLDER
  script: dotnet test