name: Katastrophic Project CI Workflow

on: [push]

jobs:
  build-and-test:
    uses: ./.github/workflows/starters/technical-starters/java/maven
    with:
      branches: main
      paths:
        - 'starters/technical-starters/java/maven/**'
        - '.github/workflows/**'
