name: katastrophic project ci workflow

# TODO Try to customize the on trigger for each job if possible
on: [push]

jobs:

# -----------------------------------------
# ----- Technical starters
# -----------------------------------------
  technical-starters_dotnet-csharp_build-and-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - uses: actions/checkout@v4
      - name: technical-starters.dotnet.csharp
        uses: ./.github/workflows/starters/technical-starters/dotnet/kata-csharp

  technical-starters_dotnet-fsharp_build-and-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - uses: actions/checkout@v4
      - name: technical-starters.dotnet.csharp
        uses: ./.github/workflows/starters/technical-starters/dotnet/kata-fsharp

  technical-starters_java-maven_build-and-test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: technical-starters.java.old.maven
        uses: ./.github/workflows/starters/technical-starters/java/old/maven

  technical-starters_java-gradle_build-and-test:
    runs-on: ubuntu-latest
    container:
      image: gradle:7.6.1-jdk11
    steps:
      - uses: actions/checkout@v4
      - name: technical-starters.java.old.gradle
        uses: ./.github/workflows/starters/technical-starters/java/old/gradle

  technical-starters_typescript_npm_build-and-test:
    runs-on: ubuntu-latest
    container:
      image: node:erbium-alpine
    steps:
      - uses: actions/checkout@v4
      - name: technical-starters.typescript.npm
        uses: ./.github/workflows/starters/technical-starters/typescript/npm

  # -----------------------------------------
  # ----- Kata starters
  # -----------------------------------------
  starters-kata-bowling-ts:
    runs-on: ubuntu-latest
    container:
      image: node:erbium-alpine
    steps:
      - uses: actions/checkout@v4
      - name: starters.kata.bowling.ts
        uses: ./.github/workflows/starters/technical-starters/typescript/npm
        with:
          project-folder: 'starters/kata-starters/kata-bowling/typescript'

  starters-kata-leap-year:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: starters.kata.leap-year
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'starters/kata-starters/kata-leap-year'

  starters-kata-roman-numerals-java:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: starters.kata.roman-numerals.java
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'starters/kata-starters/kata-roman-numerals/java'

  starters-kata-roman-numerals-ts:
    runs-on: ubuntu-latest
    container:
      image: node:erbium-alpine
    steps:
      - uses: actions/checkout@v4
      - name: starters.kata.roman-numerals.ts
        uses: ./.github/workflows/starters/technical-starters/typescript/npm
        with:
          project-folder: 'starters/kata-starters/kata-roman-numerals/typescript'

  starters-kata-rpg:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: starters.kata.rpg
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'starters/kata-starters/kata-rpg'

  starters-kata-tennis-coding:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: starters.kata.tennis.coding
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'starters/kata-starters/kata-tennis/coding-kata'

  starters-kata-tennis-refactoring:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: starters.kata.tennis.refactoring
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'starters/kata-starters/kata-tennis/refactoring-kata'

  starters-kata-worp-wrap:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: starters.kata.word-wrap
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'starters/kata-starters/kata-word-wrap'

# -----------------------------------------
# ----- Katas
# -----------------------------------------
  kata-bowling-ts:
    runs-on: ubuntu-latest
    container:
      image: node:erbium-alpine
    steps:
      - uses: actions/checkout@v4
      - name: kata.bowling.ts
        uses: ./.github/workflows/starters/technical-starters/typescript/npm
        with:
          project-folder: 'katas/kata-bowling/typescript'

  kata-leap-year:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: kata.leap-year
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'katas/kata-leap-year'

  kata-roman-numerals:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: kata.roman-numerals
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'katas/kata-roman-numerals'

  kata-rpg:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: kata.rpg
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'katas/kata-rpg'

  kata-tennis-coding:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: kata.tennis.coding
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'katas/kata-tennis/coding-kata'

  kata-tennis-refactoring:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: kata.tennis.refactoring
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'katas/kata-tennis/refactoring-kata'

  kata-word-wrap:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-adoptopenjdk-11
    steps:
      - uses: actions/checkout@v4
      - name: kata.word-wrap
        uses: ./.github/workflows/starters/technical-starters/java/old/maven
        with:
          project-folder: 'katas/kata-word-wrap'